# Enhanced Loss Configuration: balanced
# Auto-generated by integrate_enhanced_loss.py

LOSS_CONFIG = {'use_perceptual': True, 'use_edge': True, 'use_ssim': True, 'use_focal': False, 'perceptual_weight': 0.1, 'edge_weight': 0.5, 'ssim_weight': 0.5, 'segmented_weight': 1.0}

# Usage in training script:
# from loss_config_balanced import LOSS_CONFIG
# criterion = EnhancedReconstructionLoss(**LOSS_CONFIG).to(device)
